version: "3.7"
services:
  web1:
    build: ./quote_gen
    container_name: quote-gen-container
    ports:
      - "5000:5000"
    volumes:
      - web1:/home/node/webapp
    scale: 3

  web2:
    build: ./quote_disp
    container_name: quote-disp-container
    ports:
      - "5001:5001"
    depends_on:
      - web1
    volumes:
      - web2:/home/node/webapp
    scale: 3

volumes:
  web1:
  web2:
